# -*- coding: utf-8 -*-
"""Cell Viability Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yfYsIVJZTiq83jLJ7p5jhY098RM8ADE
"""

class CellViabilityAnalyzer:
    """
    Advanced cell viability analyzer optimized for blue-stained microscope images.
    Handles cells with visible boundaries and varying stain intensity.
    """

    def __init__(self,
                 dead_cell_threshold=0.50,  # HSV Value threshold (0-1)
                 min_cell_area=300,
                 max_cell_area=15000,
                 circularity_threshold=0.25):
        """
        Initialize analyzer.

        Args:
            dead_cell_threshold: Cells darker than this are considered dead (0-1)
            min_cell_area: Minimum cell size in pixels
            max_cell_area: Maximum cell size in pixels
            circularity_threshold: Minimum circularity (0-1, 1=perfect circle)
        """
        self.dead_threshold = dead_cell_threshold
        self.min_cell_area = min_cell_area
        self.max_cell_area = max_cell_area
        self.circularity_threshold = circularity_threshold

    def preprocess_image(self, image):
        """Enhance image quality and reduce noise."""
        # Apply bilateral filter to reduce noise while preserving edges
        denoised = cv2.bilateralFilter(image, 9, 75, 75)

        # Enhance contrast using CLAHE
        lab = cv2.cvtColor(denoised, cv2.COLOR_RGB2LAB)
        l, a, b = cv2.split(lab)
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        l = clahe.apply(l)
        enhanced = cv2.merge([l, a, b])
        enhanced = cv2.cvtColor(enhanced, cv2.COLOR_LAB2RGB)

        return enhanced

    def detect_cell_regions(self, image):
        """
        Detect all cell regions using adaptive thresholding and morphology.
        """
        # Convert to grayscale
        gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

        # Apply Gaussian blur
        blurred = cv2.GaussianBlur(gray, (5, 5), 0)

        # Adaptive thresholding to handle uneven illumination
        binary = cv2.adaptiveThreshold(
            blurred, 255,
            cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
            cv2.THRESH_BINARY_INV,
            blockSize=15,
            C=5
        )

        # Morphological operations to clean up
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
        binary = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel, iterations=2)
        binary = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel, iterations=1)

        # Remove small noise
        binary = morphology.remove_small_objects(binary.astype(bool),
                                                  min_size=self.min_cell_area // 2)

        return binary.astype(np.uint8) * 255

    def segment_individual_cells(self, image, binary_mask):
        """
        Segment individual cells using watershed algorithm.
        """
        # Distance transform
        dist_transform = cv2.distanceTransform(binary_mask, cv2.DIST_L2, 5)

        # Smooth distance transform
        dist_smooth = filters.gaussian(dist_transform, sigma=2)

        # Find peaks (cell centers)
        local_max = peak_local_max(
            dist_smooth,
            min_distance=15,
            threshold_rel=0.2,
            labels=binary_mask
        )

        # Create markers
        markers = np.zeros_like(binary_mask, dtype=np.int32)
        for idx, (y, x) in enumerate(local_max, start=1):
            markers[y, x] = idx

        # Dilate markers slightly
        markers = ndimage.grey_dilation(markers, size=(3, 3))

        # Watershed segmentation
        markers = segmentation.watershed(-dist_transform, markers, mask=binary_mask)

        return markers

    def extract_cell_features(self, image, markers):
        """
        Extract features for each segmented cell.
        """
        # Convert to HSV for better color analysis
        hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)

        # Get region properties
        regions = measure.regionprops(markers, intensity_image=image)

        cells = []

        for region in regions:
            # Filter by size
            if region.area < self.min_cell_area or region.area > self.max_cell_area:
                continue

            # Calculate circularity (area / convex_area)
            if region.convex_area > 0:
                circularity = region.area / region.convex_area
            else:
                circularity = 0

            # Skip non-circular objects (likely debris or cell clumps)
            if circularity < self.circularity_threshold:
                continue

            # Extract cell region
            minr, minc, maxr, maxc = region.bbox
            cell_mask = markers == region.label

            # Calculate color features
            cell_rgb = image[cell_mask]
            cell_hsv = hsv[cell_mask]

            # HSV features (H=hue, S=saturation, V=value/brightness)
            mean_hue = np.mean(cell_hsv[:, 0])
            mean_saturation = np.mean(cell_hsv[:, 1]) / 255.0
            mean_value = np.mean(cell_hsv[:, 2]) / 255.0  # Brightness

            # RGB features
            mean_rgb = np.mean(cell_rgb, axis=0)
            mean_blue = mean_rgb[2] / 255.0

            # Calculate blue ratio (blue vs other channels)
            blue_ratio = mean_blue / (np.mean(mean_rgb[:2]) / 255.0 + 1e-6)

            cells.append({
                'region': region,
                'label': region.label,
                'area': region.area,
                'centroid': region.centroid,
                'bbox': region.bbox,
                'circularity': circularity,
                'mean_value': mean_value,  # Brightness (0=dark, 1=bright)
                'mean_saturation': mean_saturation,
                'mean_blue': mean_blue,
                'blue_ratio': blue_ratio,
                'mean_rgb': mean_rgb,
                'hsv_pixels': cell_hsv # Store HSV pixels for further checks
            })

        return cells

    def classify_cells(self, cells, method='adaptive'):
        """
        Classify cells as live or dead.

        Methods:
        - 'adaptive': Automatically finds threshold using K-Means
        - 'threshold': Uses fixed threshold
        """
        if len(cells) == 0:
            return [], []

        live_cells = []
        dead_cells = []

        for cell in cells:
            # First, check if the cell is likely stained blue
            # A cell is likely stained blue if a significant portion of its pixels
            # have a blue hue and sufficient saturation.
            hsv_pixels = cell['hsv_pixels']
            if len(hsv_pixels) > 0:
                # Blue hue range in HSV (180-270 degrees, OpenCV uses 0-180)
                # Blue is around 100-130 in OpenCV HSV
                blue_hue_mask = (hsv_pixels[:, 0] >= 90) & (hsv_pixels[:, 0] <= 140)
                saturated_mask = hsv_pixels[:, 1] > 30 # Minimum saturation
                stained_pixels_count = np.sum(blue_hue_mask & saturated_mask)

                # If a certain percentage of pixels are stained, consider it stained
                is_stained = stained_pixels_count / len(hsv_pixels) > 0.4 # Adjust percentage as needed
            else:
                is_stained = False


            if not is_stained:
                # If not stained, classify as live
                live_cells.append(cell)
            elif method == 'adaptive':
                # If stained, use adaptive or threshold method
                is_dead = self._classify_single_cell_adaptive(cell)
                if is_dead:
                    dead_cells.append(cell)
                else:
                    live_cells.append(cell)
            else: # 'threshold' method
                is_dead = self._classify_single_cell_threshold(cell)
                if is_dead:
                    dead_cells.append(cell)
                else:
                    live_cells.append(cell)

        return live_cells, dead_cells


    def _classify_single_cell_threshold(self, cell):
        """Classify a single cell using fixed threshold."""
        # Dead cells: Dark (low value) + Blue (high saturation)
        is_dead = (
            cell['mean_value'] < self.dead_threshold and
            cell['mean_saturation'] > 0.2
        )
        return is_dead

    def _classify_single_cell_adaptive(self, cell):
        """Classify a single cell using K-Means on its brightness."""
        # K-Means with 2 clusters on the cell's own brightness
        brightness = np.array([pixel[2] for pixel in cell['hsv_pixels']]).reshape(-1, 1)

        if len(brightness) < 5: # Not enough pixels for meaningful clustering
            return False # Default to live if insufficient data

        try:
            kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
            labels = kmeans.fit_predict(brightness)
            centers = kmeans.cluster_centers_.flatten()

            # Identify which cluster is dead (darker)
            dead_cluster = 0 if centers[0] < centers[1] else 1

            # Count pixels in the dead cluster
            dead_pixels_count = np.sum(labels == dead_cluster)

            # If the majority of pixels belong to the darker cluster, it's dead
            return dead_pixels_count > len(labels) * 0.7 # Adjust percentage as needed

        except Exception as e:
            print(f"KMeans clustering failed for a cell: {e}")
            return False # Default to live in case of error


    def calculate_statistics(self, live_cells, dead_cells):
        """Calculate comprehensive statistics."""
        total = len(live_cells) + len(dead_cells)

        if total == 0:
            return {
                'total_cells': 0,
                'live_cells': 0,
                'dead_cells': 0,
                'live_percentage': 0.0,
                'dead_percentage': 0.0,
                'viability': 0.0
            }

        live_count = len(live_cells)
        dead_count = len(dead_cells)
        live_pct = (live_count / total) * 100
        dead_pct = (dead_count / total) * 100

        return {
            'total_cells': total,
            'live_cells': live_count,
            'dead_cells': dead_count,
            'live_percentage': live_pct,
            'dead_percentage': dead_pct,
            'viability': live_pct
        }

    def create_visualization(self, image, live_cells, dead_cells, stats):
        """Create comprehensive visualization with annotations."""
        # Create figure with subplots
        fig = plt.figure(figsize=(20, 10))

        # Original image
        ax1 = plt.subplot(2, 3, 1)
        ax1.imshow(image)
        ax1.set_title('Original Microscope Image', fontsize=14, fontweight='bold')
        ax1.axis('off')

        # Detection overlay
        ax2 = plt.subplot(2, 3, 2)
        overlay = self._create_detection_overlay(image, live_cells, dead_cells)
        ax2.imshow(overlay)
        ax2.set_title('Cell Detection with Contours', fontsize=14, fontweight='bold')
        ax2.axis('off')

        # Classification overlay
        ax3 = plt.subplot(2, 3, 3)
        classification = self._create_classification_overlay(image, live_cells, dead_cells)
        ax3.imshow(classification)
        title = f"Live/Dead Classification\n"
        title += f"Total: {stats['total_cells']} cells"
        ax3.set_title(title, fontsize=14, fontweight='bold')
        ax3.axis('off')

        # Statistics panel
        ax4 = plt.subplot(2, 3, 4)
        ax4.axis('off')
        self._add_statistics_panel(ax4, stats)

        # Brightness histogram
        ax5 = plt.subplot(2, 3, 5)
        self._plot_brightness_histogram(ax5, live_cells, dead_cells)

        # Pie chart
        ax6 = plt.subplot(2, 3, 6)
        self._plot_viability_pie(ax6, stats)

        plt.tight_layout()
        plt.show()

        return overlay, classification

    def _create_detection_overlay(self, image, live_cells, dead_cells):
        """Create overlay with all cell contours."""
        overlay = image.copy()

        # Draw all cells with contours
        all_cells = live_cells + dead_cells
        for cell in all_cells:
            minr, minc, maxr, maxc = cell['bbox']
            color = (0, 255, 0) if cell in live_cells else (255, 0, 0)

            # Draw bounding box
            cv2.rectangle(overlay, (minc, minr), (maxc, maxr), color, 2)

            # Draw centroid
            cy, cx = [int(c) for c in cell['centroid']]
            cv2.circle(overlay, (cx, cy), 5, color, -1)

        return overlay

    def _create_classification_overlay(self, image, live_cells, dead_cells):
        """Create overlay with color-coded filled masks."""
        overlay = image.copy().astype(float)

        # Create colored masks
        for cell in dead_cells:
            mask = np.zeros(image.shape[:2], dtype=bool)
            minr, minc, maxr, maxc = cell['bbox']
            mask[minr:maxr, minc:maxc] = cell['region'].image
            overlay[mask] = overlay[mask] * 0.5 + np.array([255, 0, 0]) * 0.5

        for cell in live_cells:
            mask = np.zeros(image.shape[:2], dtype=bool)
            minr, minc, maxr, maxc = cell['bbox']
            mask[minr:maxr, minc:maxc] = cell['region'].image
            overlay[mask] = overlay[mask] * 0.5 + np.array([0, 255, 0]) * 0.5

        return overlay.astype(np.uint8)

    def _add_statistics_panel(self, ax, stats):
        """Add text statistics panel."""
        ax.text(0.5, 0.95, 'CELL VIABILITY ANALYSIS',
                ha='center', va='top', fontsize=16, fontweight='bold',
                transform=ax.transAxes)

        ax.text(0.5, 0.85, '=' * 50,
                ha='center', va='top', fontsize=10, family='monospace',
                transform=ax.transAxes)

        results_text = f"""
Total Cells Detected: {stats['total_cells']}

Live Cells:  {stats['live_cells']} ({stats['live_percentage']:.1f}%)
Dead Cells:  {stats['dead_cells']} ({stats['dead_percentage']:.1f}%)

Cell Viability: {stats['viability']:.2f}%
        """

        ax.text(0.5, 0.75, results_text,
                ha='center', va='top', fontsize=14, family='monospace',
                transform=ax.transAxes,
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

        # Color legend
        ax.text(0.2, 0.2, '■', color='green', fontsize=40,
                ha='center', va='center', transform=ax.transAxes)
        ax.text(0.35, 0.2, 'Live Cells', fontsize=12,
                ha='left', va='center', transform=ax.transAxes)

        ax.text(0.2, 0.1, '■', color='red', fontsize=40,
                ha='center', va='center', transform=ax.transAxes)
        ax.text(0.35, 0.1, 'Dead Cells', fontsize=12,
                ha='left', va='center', transform=ax.transAxes)

    def _plot_brightness_histogram(self, ax, live_cells, dead_cells):
        """Plot brightness distribution."""
        if len(live_cells) > 0:
            live_brightness = [cell['mean_value'] for cell in live_cells]
            ax.hist(live_brightness, bins=20, alpha=0.7, color='green',
                   label=f'Live ({len(live_cells)})')

        if len(dead_cells) > 0:
            dead_brightness = [cell['mean_value'] for cell in dead_cells]
            ax.hist(dead_brightness, bins=20, alpha=0.7, color='red',
                   label=f'Dead ({len(dead_cells)})')

        ax.set_xlabel('Brightness (0=Dark, 1=Bright)', fontsize=11)
        ax.set_ylabel('Number of Cells', fontsize=11)
        ax.set_title('Cell Brightness Distribution', fontsize=13, fontweight='bold')
        ax.legend()
        ax.grid(alpha=0.3)

    def _plot_viability_pie(self, ax, stats):
        """Plot viability pie chart."""
        if stats['total_cells'] == 0:
            ax.text(0.5, 0.5, 'No cells detected',
                   ha='center', va='center', transform=ax.transAxes)
            return

        sizes = [stats['live_cells'], stats['dead_cells']]
        colors = ['#90EE90', '#FF6B6B']
        labels = [f"Live\n{stats['live_percentage']:.1f}%",
                 f"Dead\n{stats['dead_percentage']:.1f}%"]

        wedges, texts, autotexts = ax.pie(sizes, labels=labels, colors=colors,
                                           autopct='%d', startangle=90,
                                           textprops={'fontsize': 12, 'weight': 'bold'})

        ax.set_title(f"Cell Viability: {stats['viability']:.1f}%",
                    fontsize=13, fontweight='bold', pad=20)

    def analyze(self, image_path, method='adaptive', visualize=True):
        """
        Complete analysis pipeline.

        Args:
            image_path: Path to image or numpy array
            method: 'adaptive' (recommended) or 'threshold'
            visualize: Show detailed visualization

        Returns:
            Dictionary with all results
        """
        # Load image
        if isinstance(image_path, str):
            image = np.array(Image.open(image_path).convert('RGB'))
            print(f"Loaded image: {image.shape}")
        else:
            image = image_path
            print(f"Processing image: {image.shape}")

        # Preprocess
        print("Preprocessing image...")
        enhanced = self.preprocess_image(image)

        # Detect cells
        print("Detecting cell regions...")
        binary_mask = self.detect_cell_regions(enhanced)

        # Segment individual cells
        print("Segmenting individual cells...")
        markers = self.segment_individual_cells(enhanced, binary_mask)

        # Extract features
        print("Extracting cell features...")
        cells = self.extract_cell_features(enhanced, markers)
        print(f"   Found {len(cells)} valid cells")

        # Classify
        print(f"Classifying cells using '{method}' method...")
        live_cells, dead_cells = self.classify_cells(cells, method=method)

        # Calculate statistics
        print("Calculating statistics...")
        stats = self.calculate_statistics(live_cells, dead_cells)

        # Visualize
        if visualize:
            print("Creating visualization...")
            overlay, classification = self.create_visualization(
                image, live_cells, dead_cells, stats
            )
        else:
            overlay = self._create_detection_overlay(image, live_cells, dead_cells)
            classification = self._create_classification_overlay(image, live_cells, dead_cells)

        # Print summary
        self._print_summary(stats)

        return {
            'statistics': stats,
            'overlay': overlay,
            'classification': classification,
            'live_cells': live_cells,
            'dead_cells': dead_cells,
            'all_cells': cells
        }

    def _print_summary(self, stats):
        """Print formatted summary."""
        print("\n" + "="*70)
        print("CELL VIABILITY ANALYSIS RESULTS")
        print("="*70)
        print(f"{'Total Cells Detected:':<30} {stats['total_cells']:>5d}")
        print(f"{'Live Cells:':<30} {stats['live_cells']:>5d} ({stats['live_percentage']:>5.1f}%)")
        print(f"{'Dead Cells:':<30} {stats['dead_cells']:>5d} ({stats['dead_percentage']:>5.1f}%)")
        print("-"*70)
        print(f"{'CELL VIABILITY:':<30} {stats['viability']:>5.2f}%")
        print("="*70 + "\n")

def batch_analyze(image_folder, output_folder='results', method='adaptive'):
    """
    Process multiple images in batch.

    Args:
        image_folder: Folder containing microscope images
        output_folder: Folder to save results
        method: Classification method
    """
    import os
    from pathlib import Path

    Path(output_folder).mkdir(exist_ok=True)

    analyzer = CellViabilityAnalyzer()
    results_summary = []

    image_files = [f for f in os.listdir(image_folder)
                   if f.lower().endswith(('.png', '.jpg', '.jpeg', '.tif', '.tiff', '.bmp'))]

    print(f"\n{'='*70}")
    print(f"BATCH PROCESSING: {len(image_files)} images")
    print(f"{'='*70}\n")

    for i, filename in enumerate(image_files, 1):
        print(f"\n[{i}/{len(image_files)}] Processing: {filename}")
        print("-"*70)

        image_path = os.path.join(image_folder, filename)
        results = analyzer.analyze(image_path, method=method, visualize=False)

        # Save overlay
        overlay_img = Image.fromarray(results['overlay'])
        overlay_path = os.path.join(output_folder, f'overlay_{filename}')
        overlay_img.save(overlay_path)

        # Save classification
        class_img = Image.fromarray(results['classification'])
        class_path = os.path.join(output_folder, f'classification_{filename}')
        class_img.save(class_path)

        results_summary.append({
            'filename': filename,
            **results['statistics']
        })

    # Print summary table
    print(f"\n{'='*70}")
    print("BATCH PROCESSING SUMMARY")
    print(f"{'='*70}")
    print(f"{'Filename':<30} {'Total':<8} {'Live':<8} {'Dead':<8} {'Viability':<10}")
    print("-"*70)

    for item in results_summary:
        print(f"{item['filename']:<30} "
              f"{item['total_cells']:<8} "
              f"{item['live_cells']:<8} "
              f"{item['dead_cells']:<8} "
              f"{item['viability']:<10.2f}%")

    print(f"{'='*70}\n")
    print(f"✅ Results saved to '{output_folder}/'")

    return results_summary

def analyze_image(image_path, method='adaptive'):
    """
    Simple one-line analysis function.

    Args:
        image_path: Path to your microscope image
        method: 'adaptive' (auto-detect threshold) or 'threshold' (fixed)

    Returns:
        Results dictionary with statistics and images
    """
    analyzer = CellViabilityAnalyzer(
        dead_cell_threshold=0.35,  # Adjust if needed
        min_cell_area=100,
        max_cell_area=8000
    )

    results = analyzer.analyze(image_path, method=method, visualize=True)

    # Save results
    output_overlay = Image.fromarray(results['overlay'])
    output_class = Image.fromarray(results['classification'])

    return results
